### ISSUE TITLE
`ERROR in AppModule is not an NgModule` Angular 2.4+ is not compatible with latest typescript

### ISSUE THREAD

**Issue by garymabin** [greengerong/ng2-rebirth-ui#1]
http://stackoverflow.com/questions/41420619/error-appmodule-is-not-an-ngmodule

One workaround is to lock `typescript` to `2.0.10`

**Comment by greengerong** [comment]
Already update to `typescript: ~2.1.5`.  Could you tell again?

**Comment by greengerong** [comment]
Upgrade to 2.4.6, no this problem. Please check.
